### ISSUE TITLE
LdtpExecutionError on gettextvalue() from label

### ISSUE THREAD

**Issue by alkme** [ldtp/ldtp2#22]
I'm running simple test script which is trying to pull the text from a label which contains a version number of the application. This was a QLabel object in QT4.8, listed as a "label" object in the Application Map. I've tried getproperty(window,obj,'label') but this just returns the QT object name. gettextvalue() throws an Exception. I've pasted the list of object properties and the Exception below.

Background:
Debian 7.8 running on a Pi
QT4.8 application running in python 3.2
Test scripts running in python 2.7.3 with module LDTP 3.5.0 

Object properties 
```
lbllabelVersion
child_index: 1
label: labelVersion
parent: pnlpageConfiggroupAbout
key: lbllabelVersion
obj_index: lbl#26
class: label
```

Exception 
```
Traceback (most recent call last):
  File "test.py", line 70, in checkconfigpage
    print("text:" + gettextvalue(self.WINDOW_NAME, obj))
  File "/usr/local/lib/python2.7/dist-packages/ldtp/__init__.py", line 407, in gettextvalue
    return unicode(_remote_gettextvalue(window_name, object_name, startPosition, endPosition))
  File "/usr/local/lib/python2.7/dist-packages/ldtp/client.py", line 69, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/dist-packages/ldtp/client.py", line 189, in request
    raise LdtpExecutionError(e.faultString.encode('utf-8'))
LdtpExecutionError: Text cannot be retrieved from object [label | labelVersion].
```

I've tried a few work arounds with no success and find little on google to solve this. Thanks.

**Comment by alkme** [comment]
Likely cause of this is somewhere in PySide and not related directly to LDTP. Caused in my case by setting AccessibleNames in QT.
