### ISSUE TITLE
enterstring method does not work with "<" character

### ISSUE THREAD

**Issue by codeNameMahi** [ldtp/ldtp2#41]
I am unable to input the "<" character using the enterstring method:

`>>> ldtp.enterstring("frmWindow", "txtField", ">")`
`1`

`>>> ldtp.enterstring("frmWindow", "txtField", "<")`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ldtp/client.py", line 70, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/dist-packages/ldtp/client.py", line 187, in request
    raise e
xmlrpclib.Fault: <Fault 8002: 'string index out of range'>
`

(all special characters minus "<")
`>>> ldtp.enterstring("frmWindow", "txtField", "~!@#$%^&*()_+=-,./?[]{}|")`
`1`

(now including "<")
`>>> ldtp.enterstring("frmWindow", "txtField", "~!@#$%^&*()_+=-,./?[]{}|<>")`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ldtp/client.py", line 70, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/dist-packages/ldtp/client.py", line 187, in request
    raise e
xmlrpclib.Fault: <Fault 8002: "'KeyComboAction' object has no attribute '_func'">
`

**Comment by stuaxo** [comment]
Bit of a guess. but since this is using XMLRPC underneath it could be worth experimenting with things that might work in XML ?

```&lt;```
```&#60;```

Or construct it using CDATA

(Though some of these might get eaten by the special character code)

https://www.dvteclipse.com/documentation/svlinter/How_to_use_special_characters_in_XML.3F.html
