### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by limburgher** [ldtp/ldtp2#54]
Python 2 is going away next year, are there plans to move to Python 3?

**Comment by nagappan** [comment]
I was thinking someone ported it to support Python3, but really not, I could not find any pull request or issues, seems I have to find some time to work on it

**Comment by limburgher** [comment]
Thank you!

**Comment by nullr0ute** [comment]
It also depends on a bunch of long obsolete GNOME bindings which will also be going away because they don't support python3 such as gnome-python2* pygtk2-libglade, pyorbit, libbonobo* libgnome* and should be moved to GObject introspection based bindings

**Comment by kartikm** [comment]
Related Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933025

**Comment by schuellerf** [comment]
Please check if  https://github.com/ldtp/ldtp2/pull/58 solves your problem

**Comment by limburgher** [comment]
It would seem not:

[gwyn@fedora64 ldtp]$ ldtp 
Traceback (most recent call last):
  File "/usr/bin/ldtp", line 23, in <module>
    import ldtpd
  File "/usr/lib/python3.8/site-packages/ldtpd/__init__.py", line 38, in <module>
    from xmlrpc_daemon import XMLRPCLdtpd
ModuleNotFoundError: No module named 'xmlrpc_daemon'

**Comment by schuellerf** [comment]
Please try again - I think you didn't try my python3 branch?!
there should be a "dot" just before the xmlrpc_daemon packge:
https://github.com/schuellerf/ldtp2/blob/python3/ldtpd/__init__.py#L38
this fixed the import for me

**Comment by limburgher** [comment]
That branch seems to be based on 3.4.1; we're already on 3.5.0.

**Comment by schuellerf** [comment]
I think my branch is up to date with master and git describe also seems to be fine
```
# git describe --tags
LDTP_3.5.0-136-gee22cd1
```
@limburgher why to you think so?

**Comment by limburgher** [comment]
ls ~/rpmbuild/BUILDROOT/ldtp-3.5.0-15.fc33.x86_64/usr/lib/python3.9/site-packages/
ldtp  ldtp-3.4.1-py3.9.egg-info  ldtpd  ldtpme  ldtputils  ooldtp
[gwyn@fedora64 ldtp2]$ grep version\= setup.py 
      version="3.4.1",

**Comment by Werni2A** [comment]
I'm not a Python expert but maybe there is some kind of misunderstanding. I took a look at the PR and it looks like the version string was changed from "3.5.1" to "3.4.1" in the setup.py maybe by mistake.
@limburgher This would explain the result from your grep

**Comment by schuellerf** [comment]
Thanks @Werni2A for clarifying - I just wanted to highlight that the API might be incompatible.
@limburgher can you check if it works now? or just change the version to 3.5.1 in setup.py as it's not relevant for a test of basic functionality of my branch I think

**Comment by limburgher** [comment]
It's reporting 3.6.0 now. If I update my RPM spec to reflect that, and include the new ldtpme bits, I can build it. What's a fast test I can run on a progam I'm likely to have installed? :)

**Comment by schuellerf** [comment]
> It's reporting 3.6.0 now. If I update my RPM spec to reflect that, and include the new ldtpme bits, I can build it. What's a fast test I can run on a progam I'm likely to have installed? :)

I only use my [xfce-test](https://github.com/schuellerf/xfce-test) containers for ldtp...
